### ISSUE TITLE
 테이블뷰 안 Lottie animationView의 작동 오류

### ISSUE THREAD

**Issue by minjae-L** [minjae-L/RandomStudy#11]
# 테이블뷰 안 Lottie animationView의 작동 오류
내가 생각한 기능
- 체크버튼을 누르면 해당 셀의 배경색이 회색으로 변하고, 애니메이션이 재생된다.

현재모습
- 해당 셀의 버튼을 누르면 다른 셀의 애니메이션뷰도 반응한다.

<p align="center">
  <img src="https://github.com/minjae-L/RandomStudy/assets/54211648/eb57417b-d896-41d3-b5a9-d3ed1fe7fa55">
</p>

> 첫번째 셀의 버튼 연타 , 두번쨰 셀의 버튼 연타, 세번째 셀의 버튼 연타한 모습

- 위와같이 5개의 셀이 있을때, 첫번째 셀의 버튼을 누르면 첫번째와 다섯번째 셀이 반응한다.
- 두번째 셀의 버튼을 누르면 두번째와 네번째의 셀이 반응한다.
- 세번째는 세번째의 셀만 반응한다.
- 네번째, 다섯번째의 셀은 누르지않았음.

**Comment by Key5771** [comment]
계속 해보니까 `TodayStudyList / CompletionList` 2개의 모델에서 관리를 하고 있어서 발생하고 있는 부분인 것 같아.
`TodayStudyList`는 `CompletionList`랑 같은 모델인데 `isDone`이 더 있는 것으로 보이는데, 하나의 모델로 통합을 해야할 것 같아.
만약 완료된 것을 가져오려면 `CompletionList`를 설정하는게 아니라 `TodayStudyList`에서 `isDone`이 `true` 인 것만 가져오는 방식으로 구현하면 될 것 같은 느낌이 들어.
